### ISSUE TITLE
Unable to use parameterized ViewTree subclasses

### ISSUE THREAD

**Issue by pfn** [pfn/iota#3]
In an effort to reduce code repetition, it would be nice if one could do something like:

```scala
  case class CommonContainer[A <: ViewTree[_]](
    container: SomeViewGroup,
    toolbar: Toolbar,
    nested: A
  ) extends ViewTree[SomeViewGroup]

  case class SpecificContainer(
    container: LinearLayout,
    text: TextView
  ) extends ViewTree[LinearLayout]

  val x = ViewTree.inflate(???, CommonContainer[SpecificContainer]) // how can this syntax work? *shrug*
```

This would mean I could have the following resolve to `TextView` in `SpecificContainer`

```scala
  x.nested.text
```

**Comment by pfn** [comment]
Thanks @edmundnoble

apparently this syntax works:

```scala
  case class Parameterized[A <: ViewTree[_]](container: LinearLayout, nested: A) extends ViewTree[LinearLayout]
  case class AnItem(container: LinearLayout, text: TextView) extends ViewTree[LinearLayout]

  val x = ViewTree.inflate(this, Parameterized[AnItem] _)
  x.nested.text.setText("Whoa!")

---
[info] Compiling 1 Scala source to /Users/perryn/src/crystrak/target/android/intermediates/classes...
[warn] there were three deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[success] Total time: 4 s, completed Mar 16, 2017 3:36:24 PM
```

**Comment by pfn** [comment]
This breaks on `inflateF`

```
[warn] .../MainActivity.scala:243: ViewTree factory cannot be inspected for typesafety
[warn]     override def onCreateViewHolder(viewGroup: ViewGroup, i: Int) = ViewTreeVH(ViewTree.inflateF(self, ItemCard[UnitItem] _) {
[warn]  
[error] .../MainActivity.scala:243: exception during macro expansion: 
[error] java.lang.NullPointerException
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20$$anonfun$apply$8$$anonfun$apply$9.apply(ViewTreeMacro.scala:299)
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20$$anonfun$apply$8$$anonfun$apply$9.apply(ViewTreeMacro.scala:299)
[error] 	at scala.Option.fold(Option.scala:158)
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20$$anonfun$apply$8.apply(ViewTreeMacro.scala:299)
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20$$anonfun$apply$8.apply(ViewTreeMacro.scala:298)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:327)
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20.apply(ViewTreeMacro.scala:298)
[error] 	at iota.module.macros.ViewTreeMacro$$anonfun$20.apply(ViewTreeMacro.scala:297)
[error] 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:84)
[error] 	at iota.module.macros.ViewTreeMacro$.checkFactory(ViewTreeMacro.scala:297)
[error] 	at iota.module.macros.ViewTreeMacro$.inflateWithFactory(ViewTreeMacro.scala:319)
[error]     override def onCreateViewHolder(viewGroup: ViewGroup, i: Int) = ViewTreeVH(ViewTree.inflateF(self, ItemCard[UnitItem] _) {
```
